### ISSUE TITLE
Some question about the batch size

### ISSUE THREAD

**Issue by tangjiuqi097** [fundamentalvision/Deformable-DETR#1]
Hi, I have some question about the batch size.

First, can we run the code on 2080Ti with 2 image per card? 
I run the command "python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py " follow detr but it will raise out of memory.
I am not sure if the command "GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/r50_deformable_detr.sh" can run smoothly because I have met some problems with it.
When I run  "GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/r50_deformable_detr.sh", it raise 
"bash: ./tools/run_dist_launch.sh: Permission denied".
And when I try "GPUS_PER_NODE=8 sh ./tools/run_dist_launch.sh 8 ./configs/r50_deformable_detr.sh", it raise
 "+ GPUS=8
./tools/run_dist_launch.sh: 11: ./tools/run_dist_launch.sh: Bad substitution"

Second, will the learning rate be auto-scaled based on the batch size?
Is the default setting batch size 32 with the base learning rate 2e-4?
So if I use 8 GPU with 1 image per card, should I change the base learning rate to 5e-5?

**Comment by jackroos** [comment]
Hi @tangjiuqi097,

1. You may use batch size of 1 per GPU on 2080Ti. I have tested on 1080ti and It worked fine at first 140 iterations but indeed exceed the GPU memory of 11G after another several iteration.

2. For the permission error, you could try to run 'chmod u+x ./tools/run_dist_launch.sh' to solve it. By the way, I guess your code is cloned on Windows and then uploaded to Linux, it may cause some file format error of bash script. You had better clone the code directly on Linux instead.

3. The default batch size is 32 and the learning rate wouldn't be auto-scaled. In our experience, the learning rate shouldn't be linearly scaled w.r.t. batch size when Adam optimizer is used. I suggest you keep the learning rate of 2e-4 if the batch size doesn't change a lot.

**Comment by tangjiuqi097** [comment]
Thanks for your reply.
