### ISSUE TITLE
DETRsegm produces error: forward not implemented for ModuleList

### ISSUE THREAD

**Issue by vadimkantorov** [fundamentalvision/Deformable-DETR#103]
https://github.com/fundamentalvision/Deformable-DETR/blob/main/models/segmentation.py#L51 calls `src_proj = self.detr.input_proj(src)`, but `input_proj` is always set to a `ModuleList` at https://github.com/fundamentalvision/Deformable-DETR/blob/main/models/deformable_detr.py#L74 which inherits `Module`'s `forward()` NotImplementedError behavior: https://github.com/pytorch/pytorch/blob/4e94e84f651f7fefddd34212423a129bf56d1002/torch/nn/modules/container.py#L257

Maybe this usage in Deformable-DETR is remnant of old PyTorch behavior? What it should be changed to?

**Comment by vadimkantorov** [comment]
Should it be `src_proj = [m(x) for m, x in zip(self.detr.input_proj, src)]`?

This also doesn't work, `src` elements have incompatible dimensions:
```
(Pdb) self.detr.input_proj
ModuleList(
  (0): Sequential(
    (0): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (1): GroupNorm(32, 256, eps=1e-05, affine=True)
  )
  (1): Sequential(
    (0): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (1): GroupNorm(32, 256, eps=1e-05, affine=True)
  )
  (2): Sequential(
    (0): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (1): GroupNorm(32, 256, eps=1e-05, affine=True)
  )
  (3): Sequential(
    (0): Conv2d(2048, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (1): GroupNorm(32, 256, eps=1e-05, affine=True)
  )
)
(Pdb) [x.shape for x in src]
[torch.Size([2048, 29, 26]), torch.Size([2048, 29, 26]), torch.Size([2048, 29, 26]), torch.Size([2048, 29, 26])]
```

**Comment by vadimkantorov** [comment]
Should it be `src_proj = self.detr.input_proj[-1](src)`?

This is how `DETRsegm` processes backbone output:
```python
features, pos = self.detr.backbone(samples)

bs = features[-1].tensors.shape[0]

src, mask = features[-1].decompose()
src_proj = self.detr.input_proj(src)
hs, memory = self.detr.transformer(src_proj, mask, self.detr.query_embed.weight, pos[-1])
```

And here is how `DeformableDETR` does the same:
```python
        features, pos = self.backbone(samples)

        srcs = []
        masks = []
        for l, feat in enumerate(features):
            src, mask = feat.decompose()
            srcs.append(self.input_proj[l](src))
            masks.append(mask)
            assert mask is not None
        if self.num_feature_levels > len(srcs):
            _len_srcs = len(srcs)
            for l in range(_len_srcs, self.num_feature_levels):
                if l == _len_srcs:
                    src = self.input_proj[l](features[-1].tensors)
                else:
                    src = self.input_proj[l](srcs[-1])
                m = samples.mask
                mask = F.interpolate(m[None].float(), size=src.shape[-2:]).to(torch.bool)[0]
                pos_l = self.backbone[1](NestedTensor(src, mask)).to(src.dtype)
                srcs.append(src)
                masks.append(mask)
                pos.append(pos_l)

        query_embeds = None
        if not self.two_stage:
            query_embeds = self.query_embed.weight
        hs, init_reference, inter_references, enc_outputs_class, enc_outputs_coord_unact = self.transformer(srcs, masks, pos, query_embeds)
```

Why is there so large difference? It seems that `DETRsegm` only processes the last layer's features: `features[-1]` while `DeformableDETR` uses all the features.

Thank you!

**Comment by vadimkantorov** [comment]
Okay, it seems that this repo indeed contains broken code for segmentation, because the reported results were for segmentation.

SOLQ contains a fixed DeformableDETRsegm class: https://github.com/megvii-research/SOLQ/blob/main/models/segmentation.py

**Comment by aliman80** [comment]
Hi Thanks for your sharing of the code, Can i use this SOLQ segmentation class for custom dataset using existing deformable transformer code base
