### ISSUE TITLE
Anyone success in CUDA >= 11.0

### ISSUE THREAD

**Issue by imhgchoi** [fundamentalvision/Deformable-DETR#106]
Did anyone have success in running Deformable DETR on CUDA 11?

**Comment by amirhesamyazdi** [comment]
Did you fix your problem? Can you please elaborate how?

**Comment by imhgchoi** [comment]
I didn't actually _fix_ it. It just somehow worked in a specific environment. Here's my torch versions and stuff.

Python 3.7.11
torch 1.10.0
torchvision 0.11.1
cudatoolkit 11.1 (This should align with your cuda version)

Honestly, I can't guarantee the above versions are what made this work. But anyways, best of luck!

**Comment by shiyan-cui** [comment]
Did you fix your problem now? Can you please elaborate how?

**Comment by bimsarapathiraja** [comment]
python 3.7
torch 1.7.0
cudatoolkit 11.0 worked

**Comment by littlealuck** [comment]
> python 3.7 torch 1.7.0 cudatoolkit 11.0 worked

very good job
