### ISSUE TITLE
undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv

### ISSUE THREAD

**Issue by Ukhupacha** [fundamentalvision/Deformable-DETR#118]
Hello, 

I was compiling the Cuda Operations and launch the  `python test.py` and encounter this error.
$ python test.py
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    from functions.ms_deform_attn_func import MSDeformAttnFunction, ms_deform_attn_core_pytorch
  File "/data/ukhu/Research/CVPR-2022/Deformable-DETR/models/ops/functions/__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/data/ukhu/Research/CVPR-2022/Deformable-DETR/models/ops/functions/ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/ukhupacha/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv

I have install pytorch with 
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch

Does anybody know how can I solve this?

**Comment by fawnliu** [comment]
I solve this problem by `conda install -c conda-forge cudatoolkit-dev` and my pytorch version is 1.9.

**Comment by youarefree123** [comment]
I solve this problem by
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
