### ISSUE TITLE
lower AP for Deformable DETR

### ISSUE THREAD

**Issue by ghost** [fundamentalvision/Deformable-DETR#14]
I just follow the instructions to re-run the code for Deformable DETR, but get a lower AP.

When using a batch size 16x2, I get an AP of 44.1;

When using a batch size 32x1, I get an AP of 44.3;

When using a batch size 16x4, I get an AP of 43.5;

Also, for Deformable DETR with Iterative Refinement, I get an AP of 45.7 with batch size 16x2 (vs the released AP of 46.2).

Is this in the normal fluctuation range? 

Moreover, it seems that the batch size will influence the final performance without adjusting the learning rate.

Thanks for your response in advance.

**Comment by jackroos** [comment]
A larger batch size means fewer iterations, thus the performance may be slightly worse. And for Adam, the learning rate could not be naively adjusted by a linear scaling method. All our results are obtained using a total batch size of 32. Thank you!
