### ISSUE TITLE
ImportError: MultiScaleDeformableAttention undefined symbol

### ISSUE THREAD

**Issue by luorix1** [fundamentalvision/Deformable-DETR#141]
The make.sh under "ops" runs fine, but when I try to run my code (specifically, code similar in structure to that of MVDeTr (https://github.com/hou-yz/MVDeTr)) I get the following error.

ImportError: .conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexINS2_4HalfEEEEEPKNS_6detail12TypeMetaDataEv

I'm running pytorch 1.8.1, torchvision 0.9.1 and python 3.7 within Docker with CUDA 10.2 on a linux machine with Ubuntu 16.04.7 LTS

So far, I think my docker settings and machine settings are all sufficiently high enough to run Deformable-DETR according to the README of this repo.

Thank you very much in advance.

**Comment by iremonur** [comment]
Hi, I am currently working on COLAB with the conda environment (stated as in the ReadME) and I have met the same error, have you solved the error?

Versions:
pytorch        : 1.5.1
torchvision   : 0.6.1
CUDA          : 9.2
Python         : 3.7.10

But I have also tried with the versions:
pytorch        : 1.8.0+cu111
torchvision   : 0.9.0+cu111
CUDA          : 11.1
Python 3.7.10

**Comment by luorix1** [comment]
I forget what I did exactly, but I ended up using a different Deformable DETR ops folder from a different project and it ended p working. Probably some versioning gone wrong but I'm still not sure where... Sorry about less than helpful answer to your question.
