### ISSUE TITLE
Concatenation or summation?

### ISSUE THREAD

**Issue by BrandonHanx** [fundamentalvision/Deformable-DETR#15]
Hi, @jackroos 

I am a beginner in attention.
I wonder why you express MHAttention like this in paper:
![image](https://user-images.githubusercontent.com/37724292/102184295-30631000-3eea-11eb-8973-d3a0d6394353.png)
rather than use concatenation and Wo. Is there any particular purpose to this？

Same question for the Deformable Attention and MS Deformable Attention.

Thanks in advance.

**Comment by jackroos** [comment]
This is because mathematically the concatenation and output projection could be merged into a single projection (W_m in this formulation) from dimension C_v to C. In the implementation, the W_m actually contains these two operations. Thank you!

**Comment by jackroos** [comment]
This is because mathematically the concatenation and output projection could be expressed by a simple projection from dimension C_v to C. In the implementation, the W_m actually contains these two operations. Thank you!
