### ISSUE TITLE
CUDA memory issue

### ISSUE THREAD

**Issue by cfzd** [fundamentalvision/Deformable-DETR#16]
Hi, thanks for your great work! But I found many problems related to CUDA memory usage. 
- The memory consumptions for different GPUs are not balanced
  
  ![image](https://user-images.githubusercontent.com/17758403/102313895-6ff23080-3fac-11eb-9df2-0157913779bb.png)
  The memory consumption difference between GPUs could even higher than 3GB(I only have 11GB memory per card).

- There seems to be memory leakage
  As the training process goes on, the CUDA memory consumption becomes higher. However, the memory allocated by PyTorch is stable. Although the used CUDA memory is larger than 8GB, the memory allocated by PyTorch is only 2757MB as here:
https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/util/misc.py#L270

**Comment by jackroos** [comment]
Hi @cfzd,

It is not memory leakage, and it is related to pytorch dynamic memory allocating machenism. In my experience, the torch.cuda.max_memory_allocated() is actually lower than pytorch occupied memory. And the different memory usage across GPUs may be related to scale augmentation used during training, different batch may contain different size of images varing from 480 pixels to 800 pixels in terms of the short edge of image. (See the [data augmentation](https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/datasets/coco.py#L132) for details.)

**Comment by cfzd** [comment]
But the memory consumption varies too much to make full use of my GPU. Here are the results using `r50_deformable_detr_single_scale` config with a batch size of 2 per GPU:
![image](https://user-images.githubusercontent.com/17758403/102348324-b19acf80-3fdc-11eb-8bf8-662a3269b56e.png)
The min memory is 3.9G while the max one is 11G. 

When I use the `r50_deformable_detr` with a batch size of 2 per GPU, it will out of memory after some iterations of training.

Do you have any ideas to solve this problem?

**Comment by timmeinhardt** [comment]
I am facing the same issue. It gets a GPU OOM on 12 GB GPUs after a couple of hundred iterations. It works on 24 GB GPUs though.
Edit.: I only get an OOM error with ResNet101 on 12 GB.

**Comment by jackroos** [comment]
Sorry for that now I have no time to optimize the memory for 12GB GPUs specifically. I could just suggest you reduce the batch size.

**Comment by alanlukezic** [comment]
Hi, I am just wondering which version of Tesla V100 did you use for training (16 or 32 GB)?

**Comment by lalagood** [comment]
excuse me, please, how to reduce the batchsize ,is it?
-->
GPUS_PER_NODE=2 ./tools/run_dist_launch.sh 2 ./configs/r50_deformable_detr.sh  --batchsize_size 1

**Comment by lalagood** [comment]
> Sorry for that now I have no time to optimize the memory for 12GB GPUs specifically. I could just suggest you reduce the batch size.

excuse me, please, how to reduce the batchsize ,is it?
-->
GPUS_PER_NODE=2 ./tools/run_dist_launch.sh 2 ./configs/r50_deformable_detr.sh --batchsize_size 1
