### ISSUE TITLE
Inference Batchsize Influence the mAP

### ISSUE THREAD

**Issue by zhangxydlut** [fundamentalvision/Deformable-DETR#17]
I downloaded the official model [r50_deformable_detr-checkpoint.pth](https://drive.google.com/file/d/1nDWZWHuRwtwGden77NLM9JoWe-YisJnA/view) and run the following command
```
bash configs/r50_deformable_detr.sh  --resume modelzoo/r50_deformable_detr-checkpoint.pth --eval --batch_size=2
```
With ```--batch_size=2``` I get following result:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.379
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.602
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.402
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.201
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.408
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.535
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.317
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.519
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.557
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.327
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.595
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.771
```

When I change to ```--batch_size=8```, I get:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.419
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.623
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.457
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.244
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.453
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.571
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.338
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.560
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.601
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.382
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.644
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.802
```
It seems the batch_size influences the mAP severely.
Is that normal? Why the inference batch size can influence the evaluation result? Could you give some explanation? Thanks!

**Comment by jackroos** [comment]
Hi @zhangxydlut 

Do you use the latest code and model? There is a slight change in the code and the model is also updated accordingly. So if you use old code to evaluate the new model or use new code to evaluate old model, the mAP would change severely.

**Comment by zhangxydlut** [comment]
@jackroos  Thanks! The code I used is out-of-date. After updating the code, I get the mAP of 0.445 with ```--batch_size=2```. Thank you very much.

**Comment by zhanghang1989** [comment]
May I ask what is the major cause for this issue? 

I am trying to port deformable DETR into detectron2 and got some performance drop (~3%). I wonder it may be related to this issue.

**Comment by zhanghang1989** [comment]
NVM, problem resolved. 

I found that the top-100 boxes are selected during the inference [[link to the code](https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/deformable_detr.py#L412 )].
