### ISSUE TITLE
Why to use torch.log after obtaining output_proposals？

### ISSUE THREAD

**Issue by capsule2077** [fundamentalvision/Deformable-DETR#175]
torch.log in the third last line of the figure,why?
<img width="852" alt="image" src="https://user-images.githubusercontent.com/118047732/204969085-e5de8df4-7bdc-4353-9465-d50b08c9582b.png">

**Comment by Pujin823** [comment]
同问

**Comment by capsule2077** [comment]
> 同问

log函数的作用是把四个坐标映射回原来的值，因为4个坐标经过sigmoid，所以这里的log相当于反sigmoid函数。在misc.py文件夹下作者写了一个inverse_sigmoid函数是一样的。

**Comment by Pujin823** [comment]
> > 同问
> 
> log函数的作用是把四个坐标映射回原来的值，因为4个坐标经过sigmoid，所以这里的log相当于反sigmoid函数。在misc.py文件夹下作者写了一个inverse_sigmoid函数是一样的。

明白了，多谢
