### ISSUE TITLE
MultiScaleDeformableAttention

### ISSUE THREAD

**Issue by fff126** [fundamentalvision/Deformable-DETR#18]
Holle！Could you tell me where is the MultiScaleDeformableAttention module？

**Comment by jackroos** [comment]
Please install MultiScaleDeformableAttention module as described in [README](https://github.com/fundamentalvision/Deformable-DETR#compiling-cuda-operators).

**Comment by sarkarsayantan** [comment]
Hi @jackroos not sure where in README the installation is described for MultiScaleDeformableAttention , could you please point out specifically.

**Comment by AlirezaKh1990** [comment]
Any updates? I have the same issue.

**Comment by LeonardoAcquaroli** [comment]
Same issue...
`ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'`

**Comment by back2zack** [comment]
are there any updates regarding this issue ?

**Comment by ChihchengHsieh** [comment]
Have the same issue here.

**Comment by baby313** [comment]
> Hi @jackroos not sure where in README the installation is described for MultiScaleDeformableAttention , could you please point out specifically.

git clone https://github.com/fundamentalvision/Deformable-DETR.git
cd Deformable-DETR/models/ops
pip install .
