### ISSUE TITLE
I have successfully installed groundingdino and can run through the code using 3090, but an error will be reported when using A100 or V100.

### ISSUE THREAD

**Issue by zdxff** [fundamentalvision/Deformable-DETR#210]
error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device

**Comment by bio-mlhui** [comment]
same issue on A800

**Comment by bio-mlhui** [comment]
> same issue on A800

Rebuilding is not just re-running sh ./make.sh.  I tried pip uninstall MultiScaleDeformableAttention and rebuild, then the error disappear.

**Comment by zdxff** [comment]
thank you, my path is wrong. After I modify my cuda path, it can run.

**Comment by Geo99pro** [comment]
This may help : https://github.com/fundamentalvision/Deformable-DETR/issues/88#issuecomment-1825923432

**Comment by zdxff** [comment]
> This may help : [#88 (comment)](https://github.com/fundamentalvision/Deformable-DETR/issues/88#issuecomment-1825923432)

Thanks

**Comment by ysysys666** [comment]
@zdxff could you please tell me what mean "cuda path is wrong"? I have the same problem. thank you very much
