### ISSUE TITLE
No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by xinli-123** [fundamentalvision/Deformable-DETR#22]
![image](https://user-images.githubusercontent.com/76469672/102862353-edfe7d80-446b-11eb-91a4-e1f67579d560.png)
How should I deal with this problem

**Comment by May2333** [comment]
you should "sh make.sh" at DEFORABLE_DETR_ROOT/models/ops to build it

**Comment by jackroos** [comment]
@May2333 Thank you for answering the questions. 
@xinli-123 You need to compile the operators as described in [README](https://github.com/fundamentalvision/Deformable-DETR#compiling-cuda-operators).

**Comment by samtamoi** [comment]
![image](https://github.com/fundamentalvision/Deformable-DETR/assets/129781521/1253516f-f4fd-4d83-9fb1-e69ba0215f73)
how can i solve this problem

**Comment by RobertTang0** [comment]
> ![image](https://user-images.githubusercontent.com/129781521/246404601-1253516f-f4fd-4d83-9fb1-e69ba0215f73.png) how can i solve this problem

Have you solved this problem?

**Comment by renxiaosa00** [comment]
how to install in the environment of "conda create -n pytorch python=3.8"?

**Comment by ohhiohhi** [comment]
> ![image](https://user-images.githubusercontent.com/129781521/246404601-1253516f-f4fd-4d83-9fb1-e69ba0215f73.png) how can i solve this problem

i also met this problem, have you solved it?

**Comment by renxiaosa00** [comment]
no



At 2023-11-23 16:46:56, "ohhiohhi" ***@***.***> wrote:

how can i solve this problem

i also met this problem, have you solved it?
