### ISSUE TITLE
About the the train/test_cardinality_error

### ISSUE THREAD

**Issue by 1338199** [fundamentalvision/Deformable-DETR#24]
Hi,
   I add your focal loss method alone to the original DETR, and I found the result is not good as that of the original DETR. From the logging information, I found the training and testing cardinality errors is much higher than those of DETR. And after reading your logging records, I found that Deformable DETR seems to have the same issue. Could you explain this part. 

Thanks a lot.

**Comment by jackroos** [comment]
The calculation code of cardinality is from original DETR which last class corresponding to "no-object" class, but in Focal Loss setting, there is no the "no-object" class in the prediction, thus the calculation code is wrong.
We have tried DETR with some improvements including Focal Loss and the result (DETR-DC5+) is presented in README.
