### ISSUE TITLE
Questions about several implementation details

### ISSUE THREAD

**Issue by zb1439** [fundamentalvision/Deformable-DETR#28]
Thanks for this amazing work and code published. I am wondering the reasons for some implementation details and whether they make a huge difference to the final performance.

1.  In https://github.com/fundamentalvision/Deformable-DETR/blob/main/models/deformable_detr.py#L100
```
nn.init.constant_(self.bbox_embed[0].layers[-1].bias.data[2:], -2.0)
```
Why the box reg bias is initialized as -2.0?

2. In https://github.com/fundamentalvision/Deformable-DETR/blob/main/models/ops/modules/ms_deform_attn.py#L105 and https://github.com/fundamentalvision/Deformable-DETR/blob/main/models/ops/modules/ms_deform_attn.py#L108
```
if reference_points.shape[-1] == 2:
     offset_normalizer = torch.stack([input_spatial_shapes[..., 1], input_spatial_shapes[..., 0]], -1)
     sampling_locations = reference_points[:, :, None, :, None, :] \
                                 + sampling_offsets / offset_normalizer[None, None, None, :, None, :]
elif reference_points.shape[-1] == 4:
     sampling_locations = reference_points[:, :, None, :, None, :2] \
                                 + sampling_offsets / self.n_points * reference_points[:, :, None, :, None, 2:] * 0.5
```
It seems like the implementation for scaling sampling points on (x, y) reference points and (x, y, w, h) reference boxes are different. Does this implementation have any specific reasons?

**Comment by jackroos** [comment]
Please see details in Appendix A.4 of [our paper](https://arxiv.org/pdf/2010.04159.pdf). Both questions are already answered there.
