### ISSUE TITLE
have problem when install MultiScaleDeformableAttention

### ISSUE THREAD

**Issue by duyeouc** [fundamentalvision/Deformable-DETR#3]
I encounter problem when running test.py after ./mask.sh. 
The bug is:
ImportError: /envs/anaconda3/envs/venv/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

What causes this problem?

**Comment by Jasonkks** [comment]
Same error here

**Comment by duyeouc** [comment]
> Same error here

I have solved it.
My CUDA is 9.0, but the requirement is greater than 9.2

**Comment by Jasonkks** [comment]
> > Same error here
> 
> I have solved it.
> My CUDA is 9.0, but the requirement is greater than 9.2

Thanks. I found it to be CUDA version problem as well.

**Comment by azamshoaib** [comment]
Hi, I met the same problem, but my cuda version is 10.0. So how to solve it. Thanks

**Comment by chen-judge** [comment]
Same error with cuda 10.1. How to solved it? Thanks!

**Comment by JachyLikeCoding** [comment]
> Hi, I met the same problem, but my cuda version is 10.0. So how to solve it. Thanks



> Same error with cuda 10.1. How to solved it? Thanks!

Have you solved it? Thanks!

**Comment by ZXYFrank** [comment]
I'm using MOTR, which borrows code from this project , and my CUDA version is 10.2

only the recommended versions work for me. 

![image](https://user-images.githubusercontent.com/49837632/179389171-6401c86d-86cf-4f78-a25e-2357a3e296f0.png)


```
conda install pytorch=1.5.1 torchvision=0.6.1 cudatoolkit=9.2 -c pytorch
```

I did not change a word. It seems weird though that cudatoolkit is downgraded

Remember to run `python test.py`. All tests are passed in my case 🎉

**Comment by lebron-2016** [comment]
> I'm using MOTR, which borrows code from this project , and my CUDA version is 10.2
> 
> only the recommended versions work for me.
> 
> ![image](https://user-images.githubusercontent.com/49837632/179389171-6401c86d-86cf-4f78-a25e-2357a3e296f0.png)
> 
> ```
> conda install pytorch=1.5.1 torchvision=0.6.1 cudatoolkit=9.2 -c pytorch
> ```
> 
> I did not change a word. It seems weird though that cudatoolkit is downgraded
> 
> Remember to run `python test.py`. All tests are passed in my case 🎉

Hi, I am also trying MOTR. For MultiScaleDeformableAttention, I had no problem configuring and installing it in the Deformable DETR project. However, in the MOTR project, I also compiled it in the ops folder, but an error occurred. How did you solve it in the end? Can the ops folder in MOTR be directly replaced with the ops folder in the Deformable DETR project?
Looking forward to your reply, thank you! !
