### ISSUE TITLE
Import Error after Compilation

### ISSUE THREAD

**Issue by yingchen001** [fundamentalvision/Deformable-DETR#32]
I'm using anaconda env with pytorch 1.51 as per suggested and tried both cuda 10.1 and 9.2, but keep getting the same error after compilation. Could you suggest how to solve this problem? Thanks. 

import MultiScaleDeformableAttention as MSDA
ImportError: /home/xxx/anaconda3/envs/deform/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

**Comment by zhangjing9701** [comment]
I met the same error. Have you solved it? Thanks!

**Comment by iremonur** [comment]
Hi, I have met the same issue on COLAB, have you solved it ? 

Versions
Cuda          : 11.2
Torch          : 1.7
Torchvision : 0.8.2
