### ISSUE TITLE
Deformable DETR not fully end-to-end because of missing no_object class?

### ISSUE THREAD

**Issue by krxxxxxxxanc** [fundamentalvision/Deformable-DETR#4]
Hello,

I have another question. First I want to know if I understood the method for suppressing multiple detections and the used label loss correctly. In contrast to the original DETR, the Deformable DETR doesn't output `no_object` class. Thats why in training the target of all unmatched detections ist not a high score for `no_object` class, but a low score for every class. And thats why you use focal loss with binary cross entropy for the label loss.

My question is now, if the Deformable DETR is still fully end-to-end since I have to set a score threshold to filter out `no_object` predictions. The original DETR already outputs the correct classes without post processing.

**Comment by jackroos** [comment]
Thanks for your question, Whether to define the no_object class doesn't determine if the model is end-to-end.  End-to-end object detection means no post-processing like NMS is needed, and the network get the image as input, then output the detection results directly.
