### ISSUE TITLE
ImportError: MultiScaleDeformableAttention undefined symbol

### ISSUE THREAD

**Issue by MatteoStefanini** [fundamentalvision/Deformable-DETR#51]
Hi
I'm having troubles importing the MultiScaleDeformableAttention module.
I followed the instructions, I have pytorch 1.5.1 and cuda 9.2. 
Thanks

ImportError: .conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexINS2_4HalfEEEEEPKNS_6detail12TypeMetaDataEv

**Comment by gautamsreekumar** [comment]
Hi, could you solve this issue?

**Comment by SamMohel** [comment]
did you solve the problem?

**Comment by Gracccce** [comment]
did you solve the problem?

**Comment by luorix1** [comment]
I would also like to know how to fix this issue.
I'm running pytorch 1.8.1, torchvision 0.9.1 and python 3.7 within Docker with CUDA 10.2 on a linux machine with Ubuntu 16.04.7 LTS

**Comment by wenhaochai** [comment]
same error
pytorch 1.8.1, torchvision 0.9.1 CUDA 11.1 and python 3.7 Ubuntu 18.04

**Comment by viacheung** [comment]
> Hi I'm having troubles importing the MultiScaleDeformableAttention module. I followed the instructions, I have pytorch 1.5.1 and cuda 9.2. Thanks
> 
> ImportError: .conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexINS2_4HalfEEEEEPKNS_6detail12TypeMetaDataEv

did you solve the problem?

**Comment by LingyiHongfd** [comment]
I also met with the same error. I just delete the dictionary `conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/`, and recompile the operators. Then it works for me.

**Comment by coldmanck** [comment]
@LingyiHongfd works like magic! Thanks

**Comment by bshakya77** [comment]
> I also met with the same error. I just delete the dictionary `conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/`, and recompile the operators. Then it works for me.

I am running through the same issue. **Did you just delete the folder or did you also change any dependencies version?** Also, **how did you recompile the packages?**

**Comment by LingyiHongfd** [comment]
Yeah, I just remove the folder and did not change any dependencies version. I recompile the packages through the official command.

**Comment by bshakya77** [comment]
> Yeah, I just remove the folder and did not change any dependencies version. I recompile the packages through the official command.

Can you mention the configuration you used to train the model (`CUDA, pytorch, python, 'MultiScaleDeformableAttention '`)? 
Did you run `sh make.sh` to recompile the package after deletion?

I appreciate your help.

**Comment by LingyiHongfd** [comment]
I'm sorry that I have deleted the virtual environment, and I have forgotten these details. But I roughly remember that the CUDA version is about 11.3, PyTorch version is about 11.x, python version is about 3.8, MultiScaleDeformableAttention is just the official newest codes. I have succeeded in installing the packages in several servers with different CUDA and GPUs. 
And I run `sh make.sh` to recompile the package after deletion.

**Comment by bshakya77** [comment]
Thank you for your information. 

I am currently using CUDA 12.2., Pytorch 12.1 and Python 3.10. It is suggested to have CUDA>=9.2, Python > = 3.7. So, I think my setup satisfies their requirements. 

I am still getting the following error:
![Screenshot 2024-02-13 144459](https://github.com/fundamentalvision/Deformable-DETR/assets/61130593/7c8df225-badf-48a0-8926-478844d29d46)

**Comment by wanghangege** [comment]
> I also met with the same error. I just delete the dictionary `conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/`, and recompile the operators. Then it works for me.

It also works for me, Specifically, we should also delete the 'build' and 'MultiScaleDeformableAttention.egg-info' under the compiled file.

**Comment by carvychen** [comment]
> > I also met with the same error. I just delete the dictionary `conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/`, and recompile the operators. Then it works for me.
> 
> It also works for me, Specifically, we should also delete the 'build' and 'MultiScaleDeformableAttention.egg-info' under the compiled file.

It works for me, thank you very much

**Comment by yannqi** [comment]
> > I also met with the same error. I just delete the dictionary `conda/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/`, and recompile the operators. Then it works for me.
> 
> It also works for me, Specifically, we should also delete the 'build' and 'MultiScaleDeformableAttention.egg-info' under the compiled file.

It works for me!   Note: We should also delete the 'build' and 'MultiScaleDeformableAttention.egg-info' under the compiled file.

**Comment by Huster-Hq** [comment]
> Yeah, I just remove the folder and did not change any dependencies version. I recompile the packages through the official command.

It works for me! Amazing!
