### ISSUE TITLE
The number of class may be wrong

### ISSUE THREAD

**Issue by jshilong** [fundamentalvision/Deformable-DETR#57]
**https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/deformable_detr.py#L445**
should be 
`num_classes = 20 if args.dataset_file != 'coco' else 81 ` ？

**Comment by cloudfool** [comment]
https://github.com/facebookresearch/detr/issues/23#issuecomment-636322576

**Comment by jshilong** [comment]
> [facebookresearch/detr#23 (comment)](https://github.com/facebookresearch/detr/issues/23#issuecomment-636322576)

Thanks
