### ISSUE TITLE
How to handle background class?

### ISSUE THREAD

**Issue by songhwanjun** [fundamentalvision/Deformable-DETR#78]
I checked the code and found out a different line compared to DETR.

In DETR code, the num_class should be "+1" to handle background class.
self.class_embed = nn.Linear(hidden_dim, num_classes + 1)

But, in deformable DETR, 
self.class_embed = nn.Linear(hidden_dim, num_classes)

I am curious about how to handle the background class in your model.

**Comment by chamathabeysinghe** [comment]
This comment might help, https://github.com/fundamentalvision/Deformable-DETR/issues/72#issuecomment-886408142

**Comment by nikhilchh** [comment]
So if I have 1 class (say humans) then should I set num_classes=1 ?
