### ISSUE TITLE
Generate attention maps

### ISSUE THREAD

**Issue by timmeinhardt** [fundamentalvision/Deformable-DETR#80]
The original DETR repository allows for the generation of [attention maps](https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb). However, the `MSDeformAttn` class does not return the `attn_output_weights` as in [nn.MultiheadAttention](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html). Am I missing something or is there any example code for generating attention maps with deformable Transformers? Thank you for your response!

**Comment by GivanTsai** [comment]
Have you figured out how to generate attention map?

**Comment by 2015wan** [comment]
hello,Have you figured out how to generate attention map? (To Givan Tsai)
