### ISSUE TITLE
RuntimeError: Unrecognized tensor type ID: Autocast when training

### ISSUE THREAD

**Issue by aanavisinha** [fundamentalvision/Deformable-DETR#81]
Attempting to train the model gives me the following error once it starts training:

<img width="1439" alt="Screenshot 2021-06-22 at 3 47 52 PM" src="https://user-images.githubusercontent.com/73659591/122936147-36dab480-d371-11eb-8eed-c2fa5b680f60.png">

**Comment by aanavisinha** [comment]
Doesn't work with torchvision 0.10.0

Older versions of torch and torchvision don't work either and return a different import error:
ImportError: /home/asinha/miniconda3/envs/deformable_detr/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa

solved this issue by using torch 1.8.0 and torchvision 0.9.0

**Comment by leayz-888** [comment]
> Attempting to train the model gives me the following error once it starts training:
> 
> <img alt="Screenshot 2021-06-22 at 3 47 52 PM" width="1439" src="https://user-images.githubusercontent.com/73659591/122936147-36dab480-d371-11eb-8eed-c2fa5b680f60

> Attempting to train the model gives me the following error once it starts training:
> 
> <img alt="Screenshot 2021-06-22 at 3 47 52 PM" width="1439" src="https://user-images.githubusercontent.com/73659591/122936147-36dab480-d371-11eb-8eed-c2fa5b680f60.png">

I met the same error when i was training,have you solved this problem?
