### ISSUE TITLE
pytorch implementation

### ISSUE THREAD

**Issue by jiangxiluning** [fundamentalvision/Deformable-DETR#9]
hi, Could you explain why you suggest using Cuda implementation, instead of PyTorch implementation ?https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/ops/functions/ms_deform_attn_func.py#L41

**Comment by jackroos** [comment]
It is because the cuda version is much faster and more memory efficient than this pytorch version.

**Comment by jiangxiluning** [comment]
@jackroos hi，I am reviewing the implementation of the Cuda version. However, the backward process is hard for me to understand. May you provide any supplementary matirials to explain the process?

**Comment by Zalways** [comment]
> It is because the cuda version is much faster and more memory efficient than this pytorch version.

but the cuda version seems not surport to be exported right?i tried to exported,but failed,but got error message:
Could not export Python function call '_MSDeformAttnFunction'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
and i don't know how to do with it. @jackroos
