### ISSUE TITLE
Initialization for bbox_embed bias

### ISSUE THREAD

**Issue by ptrnn** [fundamentalvision/Deformable-DETR#93]
Hello, thank you for your great work!  I find lots of weight initialization are carefully designed and most of them are inspiring for me. However, I'm curious about how you decide on the initialization of biases (corresponding to w,h prediction) of bbox_embed  to be -2.0? I guess it's related to the range of w,h (between 0 and 1). What's the principle or intuition behind such choice?

**Comment by ZhangGongjie** [comment]
I have the same question? May I know if you have figure it out?

**Comment by LukeCho-8810** [comment]
I have this question too. Do you know why?
